# Generated by Django 3.0.8 on 2020-08-07 08:51

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='backgroundColor',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AddField(
            model_name='data',
            name='borderColor',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AddField(
            model_name='data',
            name='chartType',
            field=models.CharField(choices=[('line', 'line'), ('polar area', 'polarArea'), ('bubble', 'bubble'), ('radar', 'radar'), ('pie', 'pie'), ('bar', 'bar'), ('scatter', 'scatter'), ('doughnut', 'doughnut')], default='line', max_length=20),
        ),
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
