# Generated by Django 3.0.8 on 2020-08-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200807_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='chartType',
            field=models.CharField(choices=[('bar', 'bar'), ('scatter', 'scatter'), ('bubble', 'bubble'), ('polar area', 'polarArea'), ('radar', 'radar'), ('doughnut', 'doughnut'), ('line', 'line'), ('pie', 'pie')], default='line', max_length=20),
        ),
        migrations.AlterField(
            model_name='data',
            name='labels',
            field=models.TextField(max_length=220),
        ),
    ]
