# Generated by Django 3.0.8 on 2020-08-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200807_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chartType', models.CharField(choices=[('pie', 'pie'), ('bubble', 'bubble'), ('bar', 'bar'), ('doughnut', 'doughnut'), ('radar', 'radar'), ('line', 'line'), ('scatter', 'scatter'), ('polar area', 'polarArea')], default='line', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='chart', max_length=220)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='chartType',
        ),
        migrations.RemoveField(
            model_name='data',
            name='name',
        ),
    ]
