# Generated by Django 3.0.8 on 2020-08-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200807_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charttype',
            name='chartType',
            field=models.CharField(choices=[('radar', 'radar'), ('line', 'line'), ('polar area', 'polarArea'), ('bubble', 'bubble'), ('bar', 'bar'), ('scatter', 'scatter'), ('doughnut', 'doughnut'), ('pie', 'pie')], default='line', max_length=10),
        ),
    ]
