# Generated by Django 3.0.8 on 2020-08-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200807_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charttype',
            name='chartType',
            field=models.CharField(choices=[('pie', 'pie'), ('line', 'line'), ('bar', 'bar'), ('polar area', 'polarArea'), ('doughnut', 'doughnut'), ('radar', 'radar'), ('scatter', 'scatter'), ('bubble', 'bubble')], default='line', max_length=10),
        ),
    ]
